import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  cpSync,
  createReadStream,
  existsSync,
  lstatSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const RELEASE_SCHEMA_VERSION = 1;
export const TOOL_VERSION = 1;
export const DEFAULT_TREE_EXCLUDES = new Set([
  'artifact-tree.sha256',
  'release-manifest.json',
]);

const SHA256 = /^[a-f0-9]{64}$/;
const REVISION = /^[a-f0-9]{40}$/;

function sha256(value) {
  return createHash('sha256').update(value).digest('hex');
}

export function sha256File(file) {
  return sha256(readFileSync(file));
}

export function trackedSourceChecksum(root) {
  return sha256(execFileSync('git', ['archive', '--format=tar', 'HEAD'], {
    cwd: root,
    maxBuffer: 64 * 1024 * 1024,
  }));
}

export function createReleaseIdentity({
  sourceRevision,
  sourceTreeClean,
  sourceCommitTime,
}) {
  if (!REVISION.test(sourceRevision) || typeof sourceTreeClean !== 'boolean') {
    throw new Error('Invalid release identity source.');
  }
  const timestamp = new Date(sourceCommitTime);
  if (Number.isNaN(timestamp.valueOf())) throw new Error('Invalid source commit time.');
  const normalizedTime = timestamp.toISOString();
  const fingerprint = sha256(
    `${RELEASE_SCHEMA_VERSION}\0${sourceRevision}\0${sourceTreeClean}\0${normalizedTime}`,
  );
  return {
    schemaVersion: RELEASE_SCHEMA_VERSION,
    releaseId: `git-${fingerprint.slice(0, 16)}`,
    sourceRevision,
    sourceTreeClean,
    sourceCommitTime: normalizedTime,
  };
}

export function writeGeneratedReleaseIdentity(output, identity) {
  const validated = createReleaseIdentity(identity);
  mkdirSync(path.dirname(output), { recursive: true });
  writeFileSync(
    output,
    `// Generated by scripts/release/provenance.mjs. Do not commit.\n`
      + `export const RELEASE_IDENTITY = ${JSON.stringify(validated, null, 2)} as const;\n`,
  );
}

function collectFiles(root, current = '', files = []) {
  const directory = path.join(root, current);
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const relative = current ? `${current}/${entry.name}` : entry.name;
    const absolute = path.join(root, ...relative.split('/'));
    const stat = lstatSync(absolute);
    if (stat.isSymbolicLink()) throw new Error(`Artifact tree contains a symlink: ${relative}`);
    if (stat.isDirectory()) collectFiles(root, relative, files);
    else if (stat.isFile() && !DEFAULT_TREE_EXCLUDES.has(relative)) files.push(relative);
    else if (!stat.isFile()) throw new Error(`Artifact tree contains an unsupported file: ${relative}`);
  }
  return files;
}

async function hashFile(hash, absolute) {
  for await (const chunk of createReadStream(absolute)) hash.update(chunk);
}

export async function digestArtifactTree(root) {
  const absoluteRoot = path.resolve(root);
  const stat = lstatSync(absoluteRoot);
  if (!stat.isDirectory() || stat.isSymbolicLink()) {
    throw new Error('Artifact root must be a real directory.');
  }
  const files = collectFiles(absoluteRoot).sort((a, b) => Buffer.from(a).compare(Buffer.from(b)));
  const hash = createHash('sha256');
  for (const relative of files) {
    const pathBytes = Buffer.from(relative, 'utf8');
    const file = path.join(absoluteRoot, ...relative.split('/'));
    const size = lstatSync(file).size;
    hash.update(`path\0${pathBytes.length}\0`);
    hash.update(pathBytes);
    hash.update(`\0bytes\0${size}\0`);
    await hashFile(hash, file);
    hash.update('\0');
  }
  return { digest: hash.digest('hex'), files };
}

export function assertCleanRepository(root) {
  const status = execFileSync(
    'git',
    ['status', '--porcelain=v1', '--untracked-files=normal'],
    { cwd: root, encoding: 'utf8' },
  );
  if (status) throw new Error('Release provenance requires a clean source tree.');
}

export function normalizeCycloneDx(raw, packageJson) {
  const sbom = structuredClone(raw);
  delete sbom.serialNumber;
  if (sbom.metadata) {
    delete sbom.metadata.timestamp;
    if (sbom.metadata.component) {
      sbom.metadata.component.name = packageJson.name;
      sbom.metadata.component.version = packageJson.version;
    }
  }
  sbom.components?.sort((a, b) => String(a['bom-ref']).localeCompare(String(b['bom-ref'])));
  sbom.dependencies?.forEach((item) => item.dependsOn?.sort());
  sbom.dependencies?.sort((a, b) => String(a.ref).localeCompare(String(b.ref)));
  return sbom;
}

export function normalizePagefindEntry(raw) {
  const entry = JSON.parse(raw);
  entry.languages = Object.fromEntries(
    Object.entries(entry.languages ?? {}).sort(([a], [b]) => a.localeCompare(b)),
  );
  return JSON.stringify(entry);
}

export function validateSbom(sbom) {
  if (
    sbom?.bomFormat !== 'CycloneDX'
    || sbom?.specVersion !== '1.5'
    || sbom?.version !== 1
    || !Array.isArray(sbom.components)
    || !Array.isArray(sbom.dependencies)
  ) {
    throw new Error('Invalid CycloneDX SBOM.');
  }
  const serialized = JSON.stringify(sbom);
  if (serialized.includes('/home/') || /"timestamp"|"serialNumber"/.test(serialized)) {
    throw new Error('CycloneDX SBOM contains non-reproducible fields.');
  }
}

export function validateManifest(manifest) {
  const requiredChecksums = [
    'trackedSource',
    'packageJson',
    'packageLock',
    'config',
    'wranglerConfig',
    'artifactTree',
    'sbom',
  ];
  if (
    manifest?.schemaVersion !== RELEASE_SCHEMA_VERSION
    || manifest?.toolVersion !== TOOL_VERSION
    || !REVISION.test(manifest?.sourceRevision ?? '')
    || manifest?.sourceTreeClean !== true
    || manifest?.sbom?.scope !== 'build-dependency'
    || manifest?.sbom?.format !== 'CycloneDX'
    || manifest?.releaseIdentity?.schemaVersion !== RELEASE_SCHEMA_VERSION
    || manifest.releaseIdentity.sourceRevision !== manifest.sourceRevision
    || !requiredChecksums.every((name) => SHA256.test(manifest?.checksums?.[name] ?? ''))
  ) {
    throw new Error('Invalid release manifest.');
  }
  const serialized = JSON.stringify(manifest);
  if (
    serialized.includes('/home/')
    || /"(?:hostname|username|remoteUrl|environment|branch|secretNames?)"/i.test(serialized)
  ) {
    throw new Error('Release manifest contains a prohibited field.');
  }
}

export function createManifest({
  source,
  packageName,
  nodeVersion,
  npmVersion,
  checksums,
}) {
  const releaseIdentity = createReleaseIdentity(source);
  const manifest = {
    schemaVersion: RELEASE_SCHEMA_VERSION,
    sourceRevision: releaseIdentity.sourceRevision,
    sourceTreeClean: releaseIdentity.sourceTreeClean,
    sourceCommitTime: releaseIdentity.sourceCommitTime,
    package: { name: packageName },
    sbom: {
      scope: 'build-dependency',
      format: 'CycloneDX',
    },
    toolchain: {
      node: nodeVersion,
      npm: npmVersion,
      platform: 'linux',
      arch: 'x64',
      libc: 'glibc',
      packageManager: 'npm',
      buildCommand: 'npm run build',
    },
    checksums,
    releaseIdentity,
    toolVersion: TOOL_VERSION,
  };
  validateManifest(manifest);
  return manifest;
}

export async function verifyReleaseArtifacts(repository, output) {
  const manifest = JSON.parse(readFileSync(path.join(output, 'release-manifest.json'), 'utf8'));
  validateManifest(manifest);
  const sbomPath = path.join(output, 'sbom.cdx.json');
  const sbom = JSON.parse(readFileSync(sbomPath, 'utf8'));
  validateSbom(sbom);
  if (sha256File(sbomPath) !== manifest.checksums.sbom) {
    throw new Error('SBOM checksum does not match the release manifest.');
  }
  const inputs = {
    packageJson: 'package.json',
    packageLock: 'package-lock.json',
    wranglerConfig: 'wrangler.jsonc',
  };
  for (const [name, file] of Object.entries(inputs)) {
    if (sha256File(path.join(repository, file)) !== manifest.checksums[name]) {
      throw new Error(`${file} checksum does not match the release manifest.`);
    }
  }
  if (trackedSourceChecksum(repository) !== manifest.checksums.trackedSource) {
    throw new Error('Tracked source checksum does not match the release manifest.');
  }
  const config = await digestArtifactTree(path.join(repository, 'config'));
  if (config.digest !== manifest.checksums.config) {
    throw new Error('Configuration checksum does not match the release manifest.');
  }
  const artifact = await digestArtifactTree(path.join(output, 'deploy'));
  if (artifact.digest !== manifest.checksums.artifactTree) {
    throw new Error('Artifact tree checksum does not match the release manifest.');
  }
  const worker = path.join(output, 'deploy', '_worker.js');
  if (!existsSync(worker) || !lstatSync(worker).isFile()) {
    throw new Error('Deploy tree is missing the Cloudflare Pages _worker.js Functions entry point.');
  }
  return { manifest, sbom, artifact };
}

function git(root, args) {
  return execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim();
}

// Computes the *deployed* release identity for whatever commit this actually runs against — on
// Cloudflare that is CF_PAGES_COMMIT_SHA (the checked-out preview/production commit), which for a
// public-safe preview build differs from the internal canonical candidate's own HEAD identity (see
// docs/operations/rollback-postdeploy.md). Never substitute the canonical candidate's identity for
// this value when validating a deployed URL.
function readSourceIdentity(root) {
  const sourceRevision = process.env.CF_PAGES_COMMIT_SHA || git(root, ['rev-parse', 'HEAD']);
  const sourceTreeClean = git(root, ['status', '--porcelain=v1', '--untracked-files=normal']) === '';
  const sourceCommitTime = process.env.SOURCE_DATE_EPOCH
    ? new Date(Number(process.env.SOURCE_DATE_EPOCH) * 1000).toISOString()
    : new Date(git(root, ['show', '-s', '--format=%cI', sourceRevision])).toISOString();
  return createReleaseIdentity({ sourceRevision, sourceTreeClean, sourceCommitTime });
}

function generatedIdentityPath(root) {
  return path.join(root, 'functions/_generated/release-identity.ts');
}

export function resolveFunctionsDirectory(root) {
  const repository = path.resolve(root);
  const functions = path.resolve(repository, 'functions');
  if (
    !path.isAbsolute(functions)
    || path.relative(repository, functions) !== 'functions'
    || !lstatSync(functions).isDirectory()
  ) {
    throw new Error('Invalid repository Functions directory.');
  }
  return functions;
}

function run(root, executable, args, env = {}, cwd = root) {
  execFileSync(executable, args, { cwd, stdio: 'inherit', env: { ...process.env, ...env } });
}

function safeOutputPath(root, requested) {
  const output = path.resolve(root, requested);
  if (output === path.parse(output).root || output === path.resolve(root)) {
    throw new Error('Refusing unsafe release output directory.');
  }
  return output;
}

async function buildReleaseArtifacts(root, requestedOutput) {
  assertCleanRepository(root);
  const identity = readSourceIdentity(root);
  if (!identity.sourceTreeClean) throw new Error('Release provenance requires a clean source tree.');
  writeGeneratedReleaseIdentity(generatedIdentityPath(root), identity);

  const output = safeOutputPath(root, requestedOutput);
  rmSync(output, { recursive: true, force: true });
  mkdirSync(output, { recursive: true });
  const sourceDateEpoch = String(Math.floor(Date.parse(identity.sourceCommitTime) / 1000));
  run(root, 'npm', ['run', 'build'], {
    SOURCE_DATE_EPOCH: sourceDateEpoch,
    PUBLIC_SOURCE_DATE_EPOCH: sourceDateEpoch,
  });
  const pagefindEntry = path.join(root, 'dist/pagefind/pagefind-entry.json');
  writeFileSync(pagefindEntry, normalizePagefindEntry(readFileSync(pagefindEntry, 'utf8')));

  const deploy = path.join(output, 'deploy');
  cpSync(path.join(root, 'dist'), deploy, { recursive: true });
  const functions = resolveFunctionsDirectory(root);
  const wranglerTemporary = mkdtempSync(path.join(tmpdir(), 'portfolio-wrangler-'));
  try {
    run(root, path.join(root, 'node_modules/.bin/wrangler'), [
      'pages',
      'functions',
      'build',
      functions,
      '--outdir',
      deploy,
      '--output-routes-path',
      path.join(deploy, '_routes.json'),
      '--build-output-directory',
      path.join(root, 'dist'),
      '--compatibility-date',
      '2025-11-14',
      '--minify',
    ], {
      XDG_CONFIG_HOME: path.join(wranglerTemporary, 'xdg'),
      WRANGLER_LOG_PATH: path.join(wranglerTemporary, 'wrangler.log'),
    }, wranglerTemporary);
  } finally {
    rmSync(wranglerTemporary, { recursive: true, force: true });
  }
  // Cloudflare Pages Advanced Mode (and `wrangler pages dev`) only recognizes a compiled Functions
  // Worker at the exact path `_worker.js`; `wrangler pages functions build --outdir` writes it as
  // `index.js`. Without this rename the artifact is silently undeployable and local dev/postdeploy
  // checks fall back to live source instead of the frozen tree.
  const compiledWorker = path.join(deploy, 'index.js');
  if (!existsSync(compiledWorker)) {
    throw new Error('wrangler pages functions build did not produce the expected index.js Worker bundle.');
  }
  renameSync(compiledWorker, path.join(deploy, '_worker.js'));

  const packageJson = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
  const rawSbom = JSON.parse(execFileSync('npm', [
    'sbom',
    '--package-lock-only',
    '--sbom-format',
    'cyclonedx',
    '--sbom-type',
    'application',
  ], { cwd: root, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 }));
  const sbom = normalizeCycloneDx(rawSbom, packageJson);
  validateSbom(sbom);
  const sbomPath = path.join(output, 'sbom.cdx.json');
  writeFileSync(sbomPath, `${JSON.stringify(sbom, null, 2)}\n`);

  const artifact = await digestArtifactTree(deploy);
  const manifest = createManifest({
    source: identity,
    packageName: packageJson.name,
    nodeVersion: process.version,
    npmVersion: execFileSync('npm', ['--version'], { cwd: root, encoding: 'utf8' }).trim(),
    checksums: {
      trackedSource: trackedSourceChecksum(root),
      packageJson: sha256File(path.join(root, 'package.json')),
      packageLock: sha256File(path.join(root, 'package-lock.json')),
      config: (await digestArtifactTree(path.join(root, 'config'))).digest,
      wranglerConfig: sha256File(path.join(root, 'wrangler.jsonc')),
      artifactTree: artifact.digest,
      sbom: sha256File(sbomPath),
    },
  });
  writeFileSync(path.join(output, 'artifact-tree.sha256'), `${artifact.digest}  deploy\n`);
  writeFileSync(path.join(output, 'release-manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  await verifyReleaseArtifacts(root, output);
  console.log(`Release artifacts: ${output}`);
  console.log(`Release identity: ${identity.releaseId}`);
  console.log(`Artifact tree SHA-256: ${artifact.digest}`);
  console.log(`SBOM SHA-256: ${manifest.checksums.sbom}`);
}

async function main() {
  const root = path.resolve(fileURLToPath(new URL('../..', import.meta.url)));
  const command = process.argv[2];
  if (command === 'identity') {
    const identity = readSourceIdentity(root);
    writeGeneratedReleaseIdentity(generatedIdentityPath(root), identity);
    console.log(`${identity.releaseId} ${identity.sourceRevision} clean=${identity.sourceTreeClean}`);
    return;
  }
  if (command === 'build') {
    const outputFlag = process.argv.indexOf('--output');
    const requested = outputFlag >= 0 ? process.argv[outputFlag + 1] : '.artifacts/release';
    if (!requested) throw new Error('--output requires a directory.');
    await buildReleaseArtifacts(root, requested);
    return;
  }
  if (command === 'verify') {
    const outputFlag = process.argv.indexOf('--output');
    const requested = outputFlag >= 0 ? process.argv[outputFlag + 1] : '.artifacts/release';
    await verifyReleaseArtifacts(root, safeOutputPath(root, requested));
    console.log('Release provenance verification passed.');
    return;
  }
  throw new Error('Usage: provenance.mjs <identity|build|verify> [--output DIR]');
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  await main();
}
